bundle_id = "com.yzjsswk.Dictionary"
version = 1
author = "yzjsswk"
recipe_type = "View"
name = "Dictionary"
icon = "system:text.book.closed.fill"
command = "spell"

[[actions]]
action_type = "Shell"

    [[actions.arguments]]
    arg_type = "Plain"
    value = "/usr/local/bin/python3"

    [[actions.arguments]]
    arg_type = "File"
    value = "dictionary.py"

    [[actions.arguments]]
    arg_type = "CommandBarText"

