bundle_id = "com.yzjsswk.ShowTerminal"
version = 1
author = "yzjsswk"
recipe_type = "Task"
name = "Show Terminal"
icon = "system:apple.terminal.fill"
command = ">"

[[actions]]
action_type = "Show"

    [[actions.arguments]]
    arg_type = "Plain"
    value = "Terminal"

[[actions]]
action_type = "Back"
arguments = []

[[actions]]
action_type = "Hide"
arguments = []
