bundle_id = "com.yzjsswk.SyncGoogleBookmark"
version = 1
author = "yzjsswk"
recipe_type = "Task"
name = "Sync Google Bookmark"
icon = "system:arrow.triangle.2.circlepath"

[[actions]]
action_type = "Shell"

    [[actions.arguments]]
    arg_type = "Plain"
    value = "/usr/local/bin/python3"

    [[actions.arguments]]
    arg_type = "File"
    value = "sync_google_bookmark.py"

    [[actions.arguments]]
    arg_type = "Context"
    value = "host"

    [[actions.arguments]]
    arg_type = "Context"
    value = "port"

    [[actions.arguments]]
    arg_type = "Context"
    value = "support_path"

[[actions]]
action_type = "Back"
arguments = []

